create table if not exists TACO_ORDER (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    delivery_Name varchar(50) not null,
    delivery_Street varchar(50) not null,
    delivery_City varchar(50) not null,
    delivery_State varchar(20) not null,
    delivery_Zip varchar(10) not null,
    cc_number varchar(16) not null,
    cc_expiration varchar(5) not null,
    cc_cvv varchar(3) not null,
    placed_at timestamp not null
);
ALTER TABLE TACO_ORDER ADD PRIMARY KEY (id);

create table if not exists TACO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) not null,
    taco_order bigint not null,
    taco_order_key bigint not null,
    created_at timestamp not null
);
ALTER TABLE TACO ADD PRIMARY KEY (id);

create table if not exists INGREDIENT_REF (
    ingredient varchar(4) not null,
    taco_key bigint not null,
    taco bigint not null
);
create table if not exists INGREDIENT (
    id varchar(4) PRIMARY KEY not null,
    name varchar(25) not null,
    type varchar(10) not null
);
alter table TACO
    add foreign key (taco_order) references TACO_ORDER(id);
alter table INGREDIENT_REF
    add foreign key (ingredient) references INGREDIENT(id);
alter table INGREDIENT_REF
    add foreign key (taco) references TACO(id);